use_frameworks!

platform :ios, '8.0'

target 'YDPodDemoLib_Example' do
  pod 'YDPodDemoLib/JFNotices', :path => '../'

  target 'YDPodDemoLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
